FileVersion = 1

[Project]
Name = "microui-beef"
DefaultNamespace = "microui"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\microui_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\microui.lib"]
